### ISSUE TITLE
Does "margin" actually work?

### ISSUE THREAD

**Issue by maxgmer** [thebrandonlucas/bitcoin-qr#4]
I have bitcoin-qr element with width="160", height="160".
When I set margin="16", it looks 100% the same as margin="1".

Is it a bug?

**Comment by thebrandonlucas** [comment]
Hi @maxgmer! I think I remember running into something like this; and unfortunately it seems like it may be a problem on the underlying [QR code library](https://github.com/kozakdenys/qr-code-styling/issues?q=is%3Aissue+margin) (`margin` is a prop of that library that we just pass down).

A workaround, noted [here](https://github.com/kozakdenys/qr-code-styling/issues/209#issuecomment-2226236759), would be to just wrap the QR code in a div, and set the `padding` as desired and `background-color: white`.

**Comment by maxgmer** [comment]
> Hi @maxgmer! I think I remember running into something like this; and unfortunately it seems like it may be a problem on the underlying [QR code library](https://github.com/kozakdenys/qr-code-styling/issues?q=is%3Aissue+margin) (`margin` is a prop of that library that we just pass down).
> 
> A workaround, noted [here](https://github.com/kozakdenys/qr-code-styling/issues/209#issuecomment-2226236759), would be to just wrap the QR code in a div, and set the `padding` as desired and `background-color: white`.

I see, thanks for the tip. Will try your suggestion.
